### ISSUE TITLE
TypeError: hooks is not a function, and tags are committed before all packages are parsed

### ISSUE THREAD

**Issue by good-idea** [qiwi/semantic-release-monorepo-hooks#12]
I've set up [my repo](https://www.github.com/good-idea/sane-shopify) following the instructions, and matching the @qiwi/substrate repo as closely as possible - but I can't seem to get this to work.

At the end of each log in Travis, I see:

```
[release-hooks]: err= TypeError: hooks is not a function
    at Object.<anonymous> (/home/travis/build/good-idea/sane-shopify/.releaserc.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    ...etc
```

I have been able to publish a single package, but it is unable to authenticate with Github for later packages. [Here](https://travis-ci.org/good-idea/sane-shopify/builds/569669240#L530) is an example of a build that included a single `fix` commit, in one of the packages, then is unable to authenticate.

[Here](https://travis-ci.org/good-idea/sane-shopify/builds/569670639) is the next build, which included multiple `fix` commits. (But, I pushed these commits before the previous build had made it's `chore(release)` commit back to the repo - so, semantic release said `The local branch master is behind the remote one, therefore a new version won't be published.`). Maybe not too relevant --- but you'll see at the end that `hooks is not a function`

[Here](https://travis-ci.org/good-idea/sane-shopify/builds/569670965) is the next build. This included fix commits for the `server`, `sanity-plugin`, and `sync-utils` packages -- but, it found a change in `types` from the previous tag, and deployed that instead.

[Finally](https://travis-ci.org/good-idea/sane-shopify/builds/569681385), this build was run after adding `GH_USER` to the environment variables -- which then breaks [here](https://travis-ci.org/good-idea/sane-shopify/builds/569681385).

I'm not sure about the `hooks is not a function` problem, but, as far as the other issues go - I'm guessing that one problem is that the tags are being added to the repo before the rest of the packages have been figured out by semantic-release. I guess I'm a little lost overall - - am I missing something obvious?

**Comment by antongolub** [comment]
@good-idea, thanks for the report. It looks we finally ran into async issues similar to [#1](https://github.com/dhoulb/multi-semantic-release/issues/1) and [#48](https://github.com/qiwi/semantic-release-gh-pages-plugin/issues/48), but I can’t say for sure.

Here's the plan:
* support debug mode with extended logging to clarify the issue.
* add [ritm-hook](https://github.com/dhoulb/multi-semantic-release/pull/2) for `execa` to be allways syncronous.

**Comment by good-idea** [comment]
Thanks for your quick reply. For now, I'm rolling back and just going to use Lerna as I was before. I've removed all of my tags & commits generated while working on this from my master branch, but if you'd like to see what my config looked like when I left off, it's on this branch:

https://github.com/good-idea/sane-shopify/tree/release-config

Also, thanks for all of your work putting this together! I'm not super familiar with how semantic release works, but I'd be happy to help out with a PR when I can -- I'll keep an eye on the issues.

**Comment by antongolub** [comment]
@good-idea.
Experience has shown that we lack the resources to support several monorepo release tools, sorry.
In defense, I can say that we have made significant progress in another project — [dhoulb/multi-semantic-release](https://github.com/dhoulb/multi-semantic-release). **MSR** covers all of our cases.
